apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myd
  name: mydeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myd
    spec:
      containers:
      - image: royalsaquib/lwweb-arm:v1
        name: alwweb-arm
        resources: {}
status: {}
