apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myd
    app.kubernetes.io/instance: myapp
  name: mydeploy
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 5000
  selector:
    app: myd
  type: NodePort
status:
  loadBalancer: {}
